version: '2'
services:
    redis-cluster-local:
        image: redis:latest
        container_name: redis-cluster-local
        volumes:
            - ./docker/redis/:/data/conf
        command: bash -c "/bin/bash /data/conf/redis.sh && while true; do echo 1; sleep 1; done"
        ports:
            - 7000:7000
            - 7001:7001
            - 7002:7002
            - 7003:7003
            - 7004:7004
            - 7005:7005
